modLoader="javafml"
loaderVersion="[34,)"
license = "Creative Commons Attribution-NonCommercial ShareAlike 4.0 International License"
issueTrackerURL="https://github.com/MattCzyr/RealisticTorches/issues"
[[mods]]
    modId="realistictorches"
    version="${file.jarVersion}"
    displayName="Realistic Torches"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/realistic-torches"
    authors="ChaosTheDude"
    description='''
    Increases the difficulty of the early game by adding realism mechanics to torches.
    '''

[[dependencies.realistictorches]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
